CREATE TABLE IF NOT EXISTS ciphers (
    id SERIAL PRIMARY KEY,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    algorithm VARCHAR(255) NOT NULL,
    cipher_data JSON,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);