CREATE TABLE IF NOT EXISTS hill (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    ciphertext TEXT[][] NOT NULL,
    key INTEGER[][] NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);